export const data = {
    books: [
        {
            id: 1,
            title: "You Are a Badass",
            author: "Jen Sincero",
            terbit: 2013,
            category: "Motivasi, Pengembangan Diri",
            harga: 50.000,
            stok: 50,
            deskeripsi: "Buku ini memotivasi pembaca untuk mengatasi rasa takut dan keraguan diri, serta mengambil tindakan untuk mencapai tujuan pribadi. Sincero menggunakan bahasa yang tegas dan jujur untuk menginspirasi pembaca.",
            image: "/images/you-are-a-badass.jpg",
        },
        {
            id: 2,
            title: "atomic Habits",
            author: "James Clear",
            terbit: 2018,
            category: "Motivasi, Pengembangan Diri",
            harga: 86.000,
            stok: 50,
            deskeripsi: "Buku ini membahas konsep perubahan kecil (atomic habits) yang dapat membawa dampak besar dalam hidup. James Clear menjelaskan bagaimana kita dapat membangun kebiasaan positif, menghilangkan kebiasaan negatif, dan mencapai perubahan yang signifikan dengan berfokus pada tindakan-tindakan kecil yang diulang secara konsisten. Buku ini memberikan wawasan dan strategi praktis untuk meningkatkan produktivitas, mencapai tujuan, dan menciptakan perubahan positif dalam hidup kita melalui pengembangan kebiasaan yang kuat.",
            image: "/images/atomic-habits.jpg",
        },
        {
            id: 3,
            title: "The Power Of Now",
            author: " Eckhart Tolle",
            terbit: 1997,
            category: "Spiritualitas, Pengembangan Diri",
            harga: 60.000,
            stok: 50,
            deskeripsi: "Buku ini adalah karya yang mendalam tentang pentingnya hidup di saat ini. Eckhart Tolle mengajak pembaca untuk menjauhkan diri dari perasaan kecemasan masa lalu atau masa depan dan mengeksplorasi konsep kesadaran dalam momen sekarang. Buku ini menggugah pembaca untuk mencari kedamaian dalam kehadiran saat ini dan mengatasi perasaan stres dan cemas.",
            image: "/images/the-power-of-now.jpeg",
        },
        {
            id: 4,
            title: "Man's Search for Meaning",
            author: "Viktor E. Frankl",
            terbit: 1946,
            category: "Otobiografi, Psikologi",
            harga: 55.000,
            stok: 50,
            deskeripsi: "Viktor E. Frankl adalah seorang psikiater yang selamat dari kamp konsentrasi Nazi selama Perang Dunia II. Buku ini adalah kisah pengalamannya dan refleksinya tentang bagaimana manusia dapat menemukan makna dalam penderitaan. Frankl menunjukkan bahwa dalam mencari makna, kita dapat menemukan kekuatan untuk bertahan dalam situasi paling sulit.",
            image: "/images/man's-search-for-meaning.jpg",
        },
        {
            id: 5,
            title: "The Alchemist",
            author: "Paulo Coelho",
            terbit: 1988,
            category: "Fiksi, Inspirasi",
            harga: 80.000,
            stok: 50,
            deskeripsi: "Novel ini mengikuti perjalanan seorang gembala bernama Santiago yang mencari harta karun pribadinya. Selama perjalanannya, ia belajar tentang mimpi, takdir, dan pengorbanan diri. Buku ini penuh dengan pesan inspiratif tentang mengikuti impian dan mencari makna dalam kehidupan.",
            image: "/images/the-alchemist.jpg",
        },
        {
            id: 6,
            title: "Daring Greatly",
            author: "Brené Brown",
            terbit: 2012,
            category: "Motivasi, Pengembangan Diri",
            harga: 50.000,
            stok: 50,
            deskeripsi: "Brené Brown mengeksplorasi konsep kerentanan dan keberanian dalam buku ini. Ia menjelaskan bagaimana kerentanan dapat mengubah kehidupan kita dan bagaimana melangkah keluar dari zona nyaman kita dapat membantu kita meraih kesuksesan sejati.",
            image: "/images/daring-greatly.jpg",
        },
        {
            id: 7,
            title: "The 7 Habits of Highly Effective People",
            author: "Stephen R. Covey",
            terbit: 1989,
            category: "Psikologi, Pengembangan Diri",
            harga: 70.000,
            stok: 50,
            deskeripsi: "Stephen Covey merinci tujuh kebiasaan yang efektif dalam buku ini. Buku ini adalah panduan mendalam tentang pengembangan pribadi dan profesional, dan membantu pembaca untuk mencapai kesuksesan berkelanjutan dengan fokus pada prinsip-prinsip yang baik.",
            image: "/images/the-7-habits of-highly-effective-people.jpg",
        },
        {
            id: 8,
            title: "Awaken the Giant Within",
            author: "Tony Robbins",
            terbit: 1991,
            category: "Pengembangan Diri, Bisnis",
            harga: 65.000,
            stok: 50,
            deskeripsi: "Tony Robbins membahas pengendalian emosi dan mencapai potensi penuh dalam buku ini. Ia menawarkan panduan praktis tentang bagaimana kita dapat mengubah hidup kita dengan mengendalikan pemikiran, emosi, dan tindakan kita.",
            image: "/images/awaken-the-giant-within.jpg",
        },
        {
            id: 9,
            title: "Start with Why",
            author: "Simon Sinek",
            terbit: 2009,
            category: "Bisnis, Inspirasi",
            harga: 59.000,
            stok: 50,
            deskeripsi: "Simon Sinek mengajak pembaca untuk mencari dan memahami alasan 'mengapa' mereka melakukan apa yang mereka lakukan. Buku ini mendemonstrasikan bagaimana memahami 'mengapa' kita dapat memberikan arah dan inspirasi yang kuat dalam hidup dan bisnis.",
            image: "/images/start-with-why.jpg",
        },
        {
            id: 10,
            title: "The Four Agreements",
            author: "Miguel Ruiz",
            terbit: 1997,
            category: "Inspirasi, Pengembangan Diri",
            harga: 73.000,
            stok: 50,
            deskeripsi: "Buku ini menggambarkan empat perjanjian yang positif yang dapat mengubah cara kita memandang dunia dan diri kita sendiri. Don Miguel Ruiz mengajarkan konsep-konsep Toltec kuno untuk mencapai kebahagiaan dan kebebasan.",
            image: "/images/the-four-agreements.jpg",
        },
    ]
}